<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AccountActivityLogout</name>
   <tag></tag>
   <elementGuidId>0f68aa70-54a9-4592-a65f-35fe65db1174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.avatar-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58ab81b5-ab8c-4453-b8ac-d2ffe85d0bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar-container</value>
      <webElementGuid>06a469b9-41ce-461b-b744-68b35f38b186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AccountActivityLogout</value>
      <webElementGuid>3824bd2b-3b5a-40b3-b5f4-92238a08fb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[@class=&quot;header-container&quot;]/div[@class=&quot;userProfile-container&quot;]/div[@class=&quot;avatar-container&quot;]</value>
      <webElementGuid>398d1e4f-550c-4cc1-8cb4-8944f8009ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>072b18fa-a10d-47c6-ab71-ae9b8c1fb492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/following::div[1]</value>
      <webElementGuid>85c904f1-2c70-4943-b3e3-ea33ee60525b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XBS Admin'])[1]/following::div[2]</value>
      <webElementGuid>71e55a2f-48a5-44ad-aac6-944d2a925cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>5e15ca75-de1c-41b7-88ba-da33b2f7f04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AccountActivityLogout' or . = 'AccountActivityLogout')]</value>
      <webElementGuid>3fdae415-0ef0-4f36-adba-978824e0deee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
